### ISSUE TITLE
Error invoking action "input->input-validator#validateInput"  TypeError: Cannot set properties of undefined (setting 'innerHTML')

### ISSUE THREAD

**Issue by tomdringer** [MikeRayUX/stimulus-inline-input-validations#9]
I am using Rails 7.1 with Stimulus. When I go to add or edit data, I delete the first input (first_name) and Can't be empty appears as usual. It's when I lose focus of first_name to move to last_name that the titled error appears. The error happens whenever I tab to another input. 

The error is in this JS:

`validateInput({ target: e, target: { value: a } }) {
      let t = [], s = e.getAttribute("data-field");
      if (!s) {
        console.log('one or more <input> elements are the missing data-field="" attribute.');
        return;
      }
      let [i2] = this.errorsTargets.filter((r) => r.getAttribute("data-field") === s);
      if (e.hasAttribute("data-validations"))
        try {
          let r = e.getAttribute("data-validations");
          o2.singleQuotes.test(r) && (r = r.replace(/'/g, '"')), this.handleJSONValidations(a, JSON.parse(r), t);
        } catch (r) {
          console.log(r), console.log(`Error parsing JSON string on the data-validations attribute on data-field="${s}". Is the json string formatted properly?`);
          return;
        }
      else
        this.handleValidations(e, a, t);
      -> This line >>> i2.innerHTML = "", t.length ? t.forEach((r) => {**
        i2.innerHTML += this.errorElement(i2, r), i2.style.visibility = "visible";
      }) : i2.style.visibility = "invisible";
    }
  };
  u(c, "targets", ["field", "errors"]);`
  
  If i've left anything out, please let me know. Thanks

**Comment by MikeRayUX** [comment]
Hey Tom, sorry you're having this issue. We'll definitely get to the bottom of this!

If i'm understanding the issue correctly:
The `presence` validation message appears correctly when clearing the `first_name` field but once filled, the validation message doesn't go away when tabbing to the next field? (`last_name`)?

**Comment by tomdringer** [comment]
Thanks for your response. Actually, the first input does clear, but then validations don't appear anywhere when they should and thats when I get the js errors.

**Comment by MikeRayUX** [comment]
Ah gotcha,

Do each of your inputs have a unique `data-field` attribute name that matches it's corresponding errors container?

Example:
```ruby
<%= form.text_field :first_name, data: { input_validator_target: 'field', field: 'first_name'} %>
<div data-input-validator-target="errors" data-field="first_name"></div>

<%= form.text_field :last_name, data: { input_validator_target: 'field', field: 'last_name'} %>
<div data-input-validator-target="errors" data-field="last_name"></div>
```

**Comment by tomdringer** [comment]
Yeah so just to give you some context my form has:

`<%= form_with(model: driver, local:true, html: { multipart: true }, data: {controller: "input-validator"}) do |form| %>`

And all my inputs have the same attributes:

`<%= form.text_field :first_name,
                      data: {
                        input_validator_target:"field",
                        field: "first_name",
                        validations: json_validations_for(@driver, :first_name)
                      },
                      id: 'first_name',
                      placeholder: 'First name',
                      autocomplete: "given-name",
                      class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                   %>
                <div data-input-validator-target="errors" data-field="first_name"></div>`

**Comment by MikeRayUX** [comment]
Thanks. Going to see if I can reproduce this.

Is your `json_validations_for` helper method the same one from the README example? If not can you share it here?

**Comment by tomdringer** [comment]
Yeah its exactly the same. Thanks

**Comment by MikeRayUX** [comment]
Hmm. I'm not able to reproduce this.

![image](https://github.com/MikeRayUX/stimulus-inline-input-validations/assets/6802326/e217dbf3-9098-4ee3-beba-77a2d3d6558b)

In this case the error: `TypeError: Cannot set properties of undefined (setting 'innerHTML')` most likely means that `input-validator` is trying to append an error message element to an errors element but can't find it.

My best guess is this might be an element nesting issue. 

Can you try connecting the controller to the parent element of the form instead of the `<form>` and see if anything changes?

**Comment by tomdringer** [comment]
Yeah I wrapped it in a div, but unfortunately it didn't make a difference.

`<div data-controller="input-validator">
    <form...`

I have found something though and thats if I clear the last_name box it errors out in the console. So it seems it's just first_name that is working for me.

**Comment by MikeRayUX** [comment]
Looks like the errors element for last_name (and others) are called 'presence' instead of 'errors'.

Try changing
`<div data-input-validator-target="presence" data-field="last_name"></div>`
to
`<div data-input-validator-target="errors" data-field="last_name"></div>`

**Comment by tomdringer** [comment]
Yeah that got it! Thank you for your patience

Is errors required for each input?

**Comment by MikeRayUX** [comment]
Yay! No problem, happy to help! 

Yes, every input element that you want `input-validator` to validate must have a corresponding errors element for errors to render to.

Validations will only run on inputs that have a `data-input-validator-target="field"` attribute so if you don't want a specific input to validate, you can skip that attribute.

**Comment by tomdringer** [comment]
Excellent! Appreciate your help on this.
